"""Loom."""
import turtle
turtle.speed(100)
t = turtle


def turtle_head():
    """Pea"""
    t.color("forestgreen")
    t.begin_fill()
    t.penup()
    t.goto(0, 180)
    t.pendown()
    for i in range(4):
        t.forward(110)
        t.left(90)
    t.end_fill()
    t.penup()


def turtle_face():
    """Nägu"""
    t.goto(25, 250)
    t.pendown()
    t.color("black")
    t.begin_fill()
    for i in range(4):
        t.forward(15)
        t.left(90)
    t.penup()
    t.goto(70, 250)
    t.pendown()
    for i in range(4):
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.penup()
    t.goto(40, 250)
    t.begin_fill()
    t.pendown()
    t.forward(30)
    t.right(90)
    t.forward(15)
    t.left(90)
    t.forward(15)
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(15)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(15)
    t.left(90)
    t.forward(15)
    t.end_fill()
    t.penup()


def turtle_body():
    """Keha"""
    t.color("forestgreen")
    t.begin_fill()
    t.goto(20, 180)
    t.pendown()
    t.left(180)
    t.forward(200)
    t.right(90)
    t.forward(40)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(150)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(200)
    t.left(90)
    t.forward(70)
    t.end_fill()
    t.penup()
    t.goto(-20, -20)


def turtle_jalad():
    """Jalad"""
    t.pendown()
    t.pensize(5)
    t.pendown()
    t.left(90)
    t.forward(60)
    t.left(90)
    t.color("black")
    t.begin_fill()
    t.forward(60)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(60)
    t.left(90)
    t.forward(20)
    t.end_fill()
    t.penup()
    t.goto(130, -60)
    t.begin_fill()
    t.pendown()
    t.forward(20)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(20)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.penup()
    t.goto(0, 0)


def turtle_ears():
    """Kõrvad"""
    t.goto(25, 290)
    t.color("Green")
    t.begin_fill()
    t.pendown()
    for i in range(4):
        t.forward(15)
        t.right(90)
    t.penup()
    t.goto(70, 290)
    t.pendown()
    for i in range(4):
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.penup()


def turtle_hands():
    """Käaed"""
    t.goto(20, 130)
    t.pendown()
    t.color("darkgreen")
    t.begin_fill()
    t.right(90)
    t.forward(70)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(70)
    t.right(90)
    t.forward(15)
    t.end_fill()
    t.penup()
    t.goto(20, 60)
    t.pendown()
    t.color("black")
    t.begin_fill()
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(15)
    t.end_fill()
    t.penup()
    t.goto(85, 130)
    t.pendown()
    t.color("darkgreen")
    t.begin_fill()
    t.forward(15)
    t.right(90)
    t.forward(70)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(70)
    t.end_fill()
    t.penup()
    t.goto(85, 60)
    t.color("black")
    t.begin_fill()
    t.pendown()
    t.left(180)
    t.forward(15)
    t.left(90)
    t.forward(15)
    t.left(90)
    t.forward(15)
    t.left(90)
    t.forward(15)
    t.end_fill()
    t.penup()


def turtle_saba():
    """Saba"""
    t.goto(15, 0)
    t.color("forestgreen")
    t.pendown()
    t.begin_fill()
    for i in range(4):
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(-5, 15)
    t.color("darkgreen")
    t.begin_fill()
    t.pendown()
    for i in range(4):
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(-20, 30)
    t.color("forestgreen")
    t.begin_fill()
    t.pendown()
    for i in range(4):
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(-35, 45)
    t.color("forestgreen")
    t.begin_fill()
    t.pendown()
    for i in range(4):
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(-50, 60)
    t.color("darkgreen")
    t.begin_fill()
    t.pendown()
    for i in range(4):
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(-65, 75)
    t.color("darkgreen")
    t.begin_fill()
    t.pendown()
    for i in range(4):
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(-80, 75)
    t.color("black")
    t.begin_fill()
    t.pendown()
    for i in range(4):
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.penup()
    t.done()


turtle_head()
turtle_face()
turtle_ears()
turtle_body()
turtle_jalad()
turtle_hands()
turtle_saba()
